### ISSUE TITLE
PHP Fatal error:  Uncaught mysqli_sql_exception: ............license_util.php:206

### ISSUE THREAD

**Issue by tacop** [rpi-dotcio/phpLicenseWatcher#108] opened 2022-01-20 08:23 UTC
_PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/license_util.php:206

system environment 
--------------------------------------------------------------------------------------------
ubuntu 20.04.3  Server TLS
PHP Version At Least 7.3.0 | 7.3.33-1+ubuntu20.04.1+deb.sury.org+1
Mysql  Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using  EditLine wrapper
--------------------------------------------------------------------------------------------
Tried to exclude a week, also tried setting windows flexlm server and linux flexlm server
help debug thanks 

apache2 error log
-------------------------------------------------------------------------------------------
[Thu Jan 20 17:38:28.716936 2022] [php7:error] [pid 2372] [client 192.168.23.114:50042] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/license_util.php:206\nStack trace:\n#0 /var/www/html/license_util.php(206): mysqli->query('ALTER TABLE `fe...')\n#1 /var/www/html/license_util.php(171): db_cleanup(Object(mysqli), Array, true)\n#2 /var/www/html/license_util.php(9): update_licenses(Object(mysqli), Array)\n#3 {main}\n  thrown in /var/www/html/license_util.php on line 206
sh: 1: /var/www/html/: Permission denied  (permission granted   sudo chgrp -R www-data /var/www/html )
--------------------------------------------------------------------------------------------

php error log show  
--------------------------------------------------------------------------------------------
[20-Jan-2022 15:00:01 Asia/Chongqing] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/license_util.php:206
Stack trace:
#0 /var/www/html/license_util.php(206): mysqli->query('ALTER TABLE `fe...')
#1 /var/www/html/license_util.php(171): db_cleanup(Object(mysqli), Array, true)
#2 /var/www/html/license_util.php(9): update_licenses(Object(mysqli), Array)
#3 {main}
  thrown in /var/www/html/license_util.php on line 206_

**Comment by pbailie** [comment] 2022-01-24 16:42
So far I am unable to recreate the error.  I am wondering if the problem is from your database setup.  Please post the output of `show tables;` from your database.  You can get this from the command line.  Assuming your database is named "phplw"...
```
sudo mysql -D phplw -e "show tables;"
```

**Comment by tacop** [comment] 2022-01-25 02:47
> mysql -u root -p -D licenses -e "show tables;"

+--------------------+
| Tables_in_licenses |
+--------------------+
| available          |
| features           |
| licenses           |
| servers            |
| usage              |
+--------------------+
root@licviewrv:~#

root@licviewrv:~# mysql -V
mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
database type 
licenses    utf8mb4_general_ci

Please suggest the mysql version I am trying to install

**Comment by pbailie** [comment] 2022-01-25 14:34
My development is targeting MySQL 5.27.  MySQL 8.0 should also work.

It appears you are using MariaDB, which I am not testing any code against.  Any issue arising from MariaDB won't be addressed by me.  Others are welcome to provide support for MariaDB and contribute that code back to this project.  I have reviewed accepted community support code for MariaDB before.

As for `./lmutil lmstat -c 5280@192.168.31.95`, if that is showing on the command line that the sever is down, then that implies a problem with your network or flexlm server setup.  In which case you'll need to consult another of your org's sysadmins for help.

**Closed** 2022-02-15 02:08 UTC
Labels: question

**Comment by tacop** [comment] 2022-02-15 02:22
> My development is targeting MySQL 5.7. MySQL 8.0 should also work.
> 
> It appears you are using MariaDB, which I am not testing any code against. Any issue arising from MariaDB won't be addressed by me. Others are welcome to provide support for MariaDB and contribute that code back to this project. I have reviewed accepted community support code for MariaDB before.
> 
> As for `./lmutil lmstat -c 5280@192.168.31.95`, if that is showing on the command line that the sever is down, then that implies a problem with your network or flexlm server setup. In which case you'll need to consult another of your org's sysadmins for help.

thank you
Tried all different installations
Ubuntu 20.04 + php7.3 + mysql 5.7 - 8 (or MariaDB ) or centos 7 + php7.3 + mysql 5.7
Also confirm that ./lmutil lmstat -c port@ip or port@hostname can query flexlm server up or down normally by switching the path /usr/local/bin/lmutil through ssh
Cron is also set up normally, and it still displays in phpLicenseWatcher --> Server Administration (No servers have been polled. Make sure that license_util.php, licence_cache.php, and license_alert.php are setup on a cron schedule.) , even if executing ./lmutil The lmstat -c port@ip return shows up, and the Server Administration Status column shows DOWN, and Last Updated normally shows that it is updated every 10 minutes.
View php log will appear
[28-Jan-2022 17:40:01 Asia/Chongqing] PHP Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 in /var/www/html/license_util.php:206
Stack trace:
#0 /var/www/html/license_util.php(206): mysqli->query()
#1 /var/www/html/license_util.php(171): db_cleanup()
#2 /var/www/html/license_util.php(9): update_licenses()
#3 {main}
  thrown in /var/www/html/license_util.php on line 206
 
I can export the Ubuntu 20.04 virtual machine if I can
thanks
